/** Shared catalog matching: hide already-chosen values, then filter by the
 * draft. Prefix matches float to the top once the user is typing. */
export function filterCatalog(catalog: string[], query: string, selected: string[] = []): string[] {
  const taken = new Set(selected.map((value) => value.toLowerCase()));
  const needle = query.trim().toLowerCase();
  const matches = catalog.filter((item) => {
    if (taken.has(item.toLowerCase())) return false;
    if (!needle) return true;
    return item.toLowerCase().includes(needle);
  });
  if (!needle) return matches;
  return matches.sort((a, b) => {
    const aName = a.toLowerCase();
    const bName = b.toLowerCase();
    const aPrefix = aName.startsWith(needle);
    const bPrefix = bName.startsWith(needle);
    if (aPrefix !== bPrefix) return aPrefix ? -1 : 1;
    return a.localeCompare(b, "en", { sensitivity: "base" });
  });
}

function uniqueSorted(items: string[]): string[] {
  return [...new Set(items)].sort((a, b) => a.localeCompare(b, "en", { sensitivity: "base" }));
}

/** Skills, tools, methods, and systems across software, data, IT, pharma,
 * architecture, construction, and related trades. The input still accepts
 * anything typed; this is only a picker. */
export const SKILL_CATALOG: string[] = uniqueSorted([
  // Software & product
  ".NET",
  "A/B Testing",
  "Agile",
  "Android",
  "Angular",
  "Bash",
  "C",
  "C#",
  "C++",
  "CI/CD",
  "CSS",
  "Cypress",
  "Dart",
  "Django",
  "Docker",
  "Drupal",
  "Express",
  "Firebase",
  "Flask",
  "Flutter",
  "Git",
  "GitHub",
  "GitHub Actions",
  "GitLab",
  "Go",
  "GraphQL",
  "HTML",
  "Java",
  "JavaScript",
  "Jest",
  "Jira",
  "JUnit",
  "Kotlin",
  "Laravel",
  "Linux",
  "MATLAB",
  "NestJS",
  "Next.js",
  "Node.js",
  "Objective-C",
  "PHP",
  "Perl",
  "Playwright",
  "Prisma",
  "Python",
  "REST APIs",
  "React",
  "React Native",
  "React Query",
  "Redux",
  "Ruby",
  "Ruby on Rails",
  "Rust",
  "SASS",
  "Scala",
  "Scrum",
  "Selenium",
  "Shopify",
  "Solidity",
  "Spring",
  "Spring Boot",
  "Storybook",
  "Stripe",
  "Supabase",
  "Svelte",
  "Swift",
  "SwiftUI",
  "Tailwind CSS",
  "TypeScript",
  "Unity",
  "Unreal Engine",
  "Vercel",
  "Vite",
  "Vue",
  "Webflow",
  "Webpack",
  "WordPress",
  "XML",
  "YAML",
  "gRPC",
  "jQuery",
  // Cloud, DevOps, IT
  "AWS",
  "Active Directory",
  "Ansible",
  "Azure",
  "Backup and Recovery",
  "CircleCI",
  "Cloudflare",
  "CompTIA",
  "Cybersecurity",
  "DHCP",
  "DNS",
  "Disaster Recovery",
  "Firewall",
  "GCP",
  "Grafana",
  "Helm",
  "Help Desk",
  "Hyper-V",
  "ITIL",
  "Identity Management",
  "Information Security",
  "Intune",
  "Jenkins",
  "Kubernetes",
  "LAN",
  "Load Balancing",
  "Microsoft 365",
  "Network Monitoring",
  "Network Security",
  "Nginx",
  "Office 365",
  "Okta",
  "PowerShell",
  "Prometheus",
  "Routing and Switching",
  "SCCM",
  "SIEM",
  "SSO",
  "ServiceNow",
  "Splunk",
  "TCP/IP",
  "Terraform",
  "VLAN",
  "VPN",
  "VMware",
  "VoIP",
  "WAN",
  "Windows Server",
  "Wireless Networking",
  "Wireshark",
  "iOS",
  // Data & databases
  "Airflow",
  "Apache Spark",
  "BigQuery",
  "Business Intelligence",
  "Cassandra",
  "DAX",
  "Data Analysis",
  "Data Governance",
  "Data Mining",
  "Data Modeling",
  "Data Visualization",
  "Data Warehousing",
  "Databricks",
  "DynamoDB",
  "ETL",
  "Elasticsearch",
  "Excel",
  "Hadoop",
  "Hive",
  "Looker",
  "MariaDB",
  "MongoDB",
  "MySQL",
  "NoSQL",
  "NumPy",
  "Oracle",
  "PL/SQL",
  "Pandas",
  "PostgreSQL",
  "Power BI",
  "Power Query",
  "R",
  "Redis",
  "Redshift",
  "SQL",
  "SQL Server",
  "SQLite",
  "SSAS",
  "SSIS",
  "SSRS",
  "Scikit-learn",
  "Snowflake",
  "Statistics",
  "T-SQL",
  "Tableau",
  "dbt",
  // Pharma, clinical, lab
  "CAPA",
  "Cell Culture",
  "Cerner",
  "Clinical Research",
  "Clinical Trials",
  "Compounding",
  "Drug Development",
  "ELISA",
  "EMR",
  "Epic",
  "FDA Regulations",
  "Formulation",
  "GCP",
  "GDP",
  "GLP",
  "GMP",
  "HIPAA",
  "HPLC",
  "ICH Guidelines",
  "LIMS",
  "Medical Writing",
  "PCR",
  "Patient Care",
  "Pharmacovigilance",
  "Quality Assurance",
  "Quality Control",
  "Regulatory Affairs",
  "SAS",
  "SOP Writing",
  "Sterile Manufacturing",
  "Western Blot",
  // Architecture, BIM, design
  "3D Modeling",
  "Adobe Illustrator",
  "Adobe InDesign",
  "Adobe Photoshop",
  "Adobe XD",
  "ArchiCAD",
  "AutoCAD",
  "BIM",
  "Blender",
  "Building Codes",
  "Canva",
  "Construction Documents",
  "Figma",
  "Grasshopper",
  "Hand Drafting",
  "Illustrator",
  "InDesign",
  "Interior Design",
  "LEED",
  "Lumion",
  "Navisworks",
  "Photoshop",
  "Rendering",
  "Revit",
  "Rhino",
  "Site Planning",
  "Sketch",
  "SketchUp",
  "Urban Design",
  "V-Ray",
  // Construction, trades, manufacturing
  "Bluebeam",
  "Blueprints",
  "Civil 3D",
  "Concrete",
  "Contract Administration",
  "Electrical Systems",
  "Estimating",
  "HVAC",
  "Heavy Equipment",
  "Inventory Management",
  "Kaizen",
  "Lean",
  "Lean Construction",
  "Logistics",
  "MEP",
  "MS Project",
  "OSHA",
  "Plumbing",
  "Primavera P6",
  "Procore",
  "Procurement",
  "Quantity Surveying",
  "Safety Management",
  "Scaffolding",
  "Scheduling",
  "Six Sigma",
  "SolidWorks",
  "Steel",
  "Supply Chain",
  "Surveying",
  "Welding",
  // Business tools
  "Confluence",
  "Contentful",
  "Google Analytics",
  "Hibernate",
  "HubSpot",
  "Kafka",
  "Keras",
  "Less",
  "Notion",
  "PowerPoint",
  "PyTorch",
  "QuickBooks",
  "Salesforce",
  "SAP",
  "TensorFlow",
  "Zapier",
]);

/** Job titles across software, data, IT, pharma, architecture, construction,
 * healthcare, and business. */
export const ROLE_CATALOG: string[] = uniqueSorted([
  "Account Executive",
  "Account Manager",
  "Accountant",
  "Administrative Assistant",
  "AI Engineer",
  "Analytics Engineer",
  "Android Developer",
  "Architect",
  "Architectural Designer",
  "Architectural Intern",
  "Auditor",
  "Backend Engineer",
  "Bank Teller",
  "Barista",
  "BIM Coordinator",
  "BIM Manager",
  "Biochemist",
  "Brand Manager",
  "Business Analyst",
  "Business Development Manager",
  "Business Intelligence Analyst",
  "Carpenter",
  "Cashier",
  "CEO",
  "CFO",
  "Chemist",
  "Civil Engineer",
  "Clinical Pharmacist",
  "Clinical Research Associate",
  "Cloud Architect",
  "Cloud Engineer",
  "Community Manager",
  "Construction Manager",
  "Construction Worker",
  "Consultant",
  "Content Writer",
  "Copywriter",
  "CTO",
  "Customer Success Manager",
  "Customer Support Specialist",
  "Cybersecurity Analyst",
  "Data Analyst",
  "Data Architect",
  "Data Engineer",
  "Data Scientist",
  "Database Administrator",
  "Database Architect",
  "Database Developer",
  "Dental Assistant",
  "Dentist",
  "Designer",
  "Desktop Support Specialist",
  "DevOps Engineer",
  "Director of Engineering",
  "Drafter",
  "Electrician",
  "Electrical Engineer",
  "Engineering Manager",
  "Estimator",
  "ETL Developer",
  "Executive Assistant",
  "Finance Manager",
  "Financial Analyst",
  "Foreman",
  "Formulation Scientist",
  "Founder",
  "Frontend Engineer",
  "Full Stack Engineer",
  "Graphic Designer",
  "Hardware Engineer",
  "Head of Product",
  "Help Desk Technician",
  "HR Generalist",
  "HR Manager",
  "HVAC Technician",
  "Information Security Analyst",
  "Infrastructure Engineer",
  "Insurance Agent",
  "Intern",
  "Interior Designer",
  "iOS Developer",
  "IT Director",
  "IT Manager",
  "IT Support Specialist",
  "Lab Technician",
  "Landscape Architect",
  "Legal Counsel",
  "Loan Officer",
  "Machine Learning Engineer",
  "Manufacturing Technician",
  "Marketing Coordinator",
  "Marketing Manager",
  "Mechanical Engineer",
  "Medical Assistant",
  "Medical Science Liaison",
  "Microbiologist",
  "Mobile Engineer",
  "Network Administrator",
  "Network Architect",
  "Network Engineer",
  "NOC Technician",
  "Nurse Practitioner",
  "Occupational Therapist",
  "Office Manager",
  "Operations Manager",
  "Owner",
  "Paralegal",
  "Pharmaceutical Scientist",
  "Pharmacist",
  "Pharmacovigilance Specialist",
  "Pharmacy Technician",
  "Physical Therapist",
  "Physician",
  "Plumber",
  "Principal Architect",
  "Principal Software Engineer",
  "Process Engineer",
  "Product Analyst",
  "Product Designer",
  "Product Manager",
  "Product Marketing Manager",
  "Production Supervisor",
  "Program Manager",
  "Project Architect",
  "Project Coordinator",
  "Project Engineer",
  "Project Manager",
  "Property Manager",
  "QA Engineer",
  "Quality Assurance Analyst",
  "Quality Assurance Specialist",
  "Quality Control Analyst",
  "Quantity Surveyor",
  "Real Estate Agent",
  "Recruiter",
  "Registered Nurse",
  "Regulatory Affairs Specialist",
  "Research Analyst",
  "Research Assistant",
  "Research Scientist",
  "Retail Associate",
  "Safety Officer",
  "Sales Associate",
  "Sales Manager",
  "Sales Representative",
  "Scheduler",
  "Security Engineer",
  "Senior Data Analyst",
  "Senior Product Manager",
  "Senior Software Engineer",
  "Site Engineer",
  "Site Reliability Engineer",
  "Site Supervisor",
  "SOC Analyst",
  "Software Developer",
  "Software Engineer",
  "Software Engineer Intern",
  "Software Engineering Intern",
  "Solutions Architect",
  "Staff Software Engineer",
  "Store Manager",
  "Structural Engineer",
  "Student Researcher",
  "Superintendent",
  "Support Engineer",
  "Surveyor",
  "Systems Administrator",
  "Systems Analyst",
  "Systems Engineer",
  "Teacher",
  "Technical Lead",
  "Technical Support Engineer",
  "Technical Writer",
  "Telecom Engineer",
  "Tutor",
  "UI Designer",
  "Urban Planner",
  "UX Designer",
  "UX Researcher",
  "Validation Engineer",
  "Vice President of Engineering",
  "Video Editor",
  "Warehouse Associate",
  "Web Developer",
  "Wireless Engineer",
]);

export const DEGREE_CATALOG: string[] = uniqueSorted([
  "A.A.",
  "A.A.S.",
  "A.S.",
  "Associate of Applied Science",
  "Associate of Arts",
  "Associate of Science",
  "B.A.",
  "B.Arch",
  "B.B.A.",
  "B.Eng",
  "B.F.A.",
  "B.S.",
  "B.S.N.",
  "Bachelor of Architecture",
  "Bachelor of Arts",
  "Bachelor of Engineering",
  "Bachelor of Fine Arts",
  "Bachelor of Science",
  "Certificate",
  "D.D.S.",
  "D.V.M.",
  "Diploma",
  "Ed.D.",
  "GED",
  "High School Diploma",
  "J.D.",
  "M.A.",
  "M.Arch",
  "M.B.A.",
  "M.Ed",
  "M.Eng",
  "M.F.A.",
  "M.P.H.",
  "M.S.",
  "M.S.N.",
  "Master of Architecture",
  "Master of Business Administration",
  "Master of Engineering",
  "Master of Science",
  "M.D.",
  "Ph.D.",
  "Pharm.D.",
  "Postgraduate Diploma",
]);

export const FIELD_CATALOG: string[] = uniqueSorted([
  "Accounting",
  "Architecture",
  "Biochemistry",
  "Biology",
  "Biotechnology",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Communications",
  "Computer Networks",
  "Computer Science",
  "Construction Management",
  "Cybersecurity",
  "Data Science",
  "Database Administration",
  "Economics",
  "Education",
  "Electrical Engineering",
  "English",
  "Environmental Science",
  "Finance",
  "Geology",
  "Graphic Design",
  "History",
  "Industrial Design",
  "Information Systems",
  "Information Technology",
  "Interior Design",
  "Law",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Medicine",
  "Microbiology",
  "Network Engineering",
  "Nursing",
  "Pharmaceutical Sciences",
  "Pharmacology",
  "Pharmacy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Health",
  "Sociology",
  "Statistics",
  "Urban Planning",
]);

export const COURSE_CATALOG: string[] = uniqueSorted([
  "Algorithms",
  "Anatomy",
  "Architectural Design Studio",
  "Biochemistry",
  "Building Construction",
  "Calculus",
  "Clinical Pharmacy",
  "Computer Networks",
  "Construction Methods",
  "Data Structures",
  "Database Systems",
  "Dynamics",
  "Financial Accounting",
  "HVAC Design",
  "Linear Algebra",
  "Microbiology",
  "Operating Systems",
  "Organic Chemistry",
  "Pharmacology",
  "Project Management",
  "Statics",
  "Statistics",
  "Structural Analysis",
  "Thermodynamics",
]);

export const CERTIFICATION_CATALOG: string[] = uniqueSorted([
  "Autodesk Certified Professional",
  "AWS Certified Cloud Practitioner",
  "AWS Certified Developer",
  "AWS Certified Solutions Architect",
  "Azure Administrator",
  "Azure Fundamentals",
  "BLS",
  "CAPM",
  "CCNA",
  "CCNP",
  "CDL",
  "CFA",
  "CISM",
  "CISSP",
  "CompTIA A+",
  "CompTIA Network+",
  "CompTIA Security+",
  "CPA",
  "CPR",
  "First Aid",
  "Google Cloud Associate",
  "Google Data Analytics",
  "ITIL Foundation",
  "LEED AP",
  "LEED Green Associate",
  "Microsoft Certified: Azure Fundamentals",
  "NCLEX",
  "OSHA 10",
  "OSHA 30",
  "PE",
  "PMP",
  "Revit Certified Professional",
  "SHRM-CP",
  "Six Sigma Black Belt",
  "Six Sigma Green Belt",
  "SolidWorks CSWA",
]);

export const CERTIFICATION_ISSUER_CATALOG: string[] = uniqueSorted([
  "Amazon Web Services",
  "American Heart Association",
  "American Red Cross",
  "Autodesk",
  "Cisco",
  "CompTIA",
  "Google",
  "IEEE",
  "ISACA",
  "(ISC)²",
  "Microsoft",
  "NABP",
  "NCARB",
  "Oracle",
  "OSHA",
  "PMI",
  "Red Hat",
  "SAP",
  "State Board of Pharmacy",
  "USGBC",
]);

export const LANGUAGE_CATALOG: string[] = uniqueSorted([
  "American Sign Language",
  "Arabic",
  "Bengali",
  "Cantonese",
  "Czech",
  "Dutch",
  "English",
  "French",
  "German",
  "Greek",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Indonesian",
  "Italian",
  "Japanese",
  "Korean",
  "Mandarin",
  "Persian",
  "Polish",
  "Portuguese",
  "Romanian",
  "Russian",
  "Spanish",
  "Swahili",
  "Swedish",
  "Tagalog",
  "Tamil",
  "Telugu",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Vietnamese",
]);

export const SOFT_SKILL_CATALOG: string[] = uniqueSorted([
  "Adaptability",
  "Attention to Detail",
  "Coaching",
  "Collaboration",
  "Communication",
  "Conflict Resolution",
  "Creativity",
  "Critical Thinking",
  "Customer Service",
  "Decision Making",
  "Empathy",
  "Emotional Intelligence",
  "Leadership",
  "Mentoring",
  "Multitasking",
  "Negotiation",
  "Organization",
  "Presentation",
  "Problem Solving",
  "Public Speaking",
  "Stakeholder Management",
  "Teamwork",
  "Time Management",
  "Work Ethic",
]);

export const HOBBY_CATALOG: string[] = uniqueSorted([
  "Astronomy",
  "Basketball",
  "Camping",
  "Chess",
  "Cooking",
  "Cycling",
  "Dance",
  "Film",
  "Gardening",
  "Hiking",
  "Music",
  "Painting",
  "Photography",
  "Reading",
  "Running",
  "Soccer",
  "Swimming",
  "Tennis",
  "Theater",
  "Travel",
  "Volunteering",
  "Woodworking",
  "Writing",
  "Yoga",
]);
